### PR TITLE
modify samples for webworks.js packager change

### PR DESCRIPTION
**Pull request by bryanhiggins**

### CODE REVIEW

**Comment by mdandrea** [comment]
@bryanhiggins The Push Capture sample is up to date on the public site, so please don't modify it. :)

**Comment by bryanhiggins** [comment]
@mdandrea Yep, all apps on the blackberry repo are up to date already. This is an old branch which I forgot to merge when the packager change went out.

**Comment by mdandrea** [comment]
Ok, but do you know if this private repo is ever merged into the public one?  Because our pushCapture sample looks nothing like this now.  We do the update ourselves to the public repo.

**Comment by nukulb** [comment]
this repo should be killed 
Lets just start going straight to blackberry

@bryanhiggins - fork and apply your change and retarget.

**Comment by bryanhiggins** [comment]
@nukulb blackberry is already up-to-date. Can we go ahead and delete this repo?

**Comment by nukulb** [comment]
yup, I will kill it.

**Pull request closed without merging**
