### PR TITLE
Changed the invoke target key

### PR DESCRIPTION
**Pull request by mdandrea**
Had to change the invoke target key to allow for signing since using 'net.rim' at the start is not allowed.

### CODE REVIEW

**Comment by nukulb** [comment]
Are you sure signing works for invoke target?
I thought invoke target was not allowed externally yet?

**Comment by nukulb** [comment]
@astanley - does this fix your signing issue?

**Comment by mdandrea** [comment]
Push needs the invoke target or it won't work.  Signing passes after I switched the "net.rim" prefix to something else.

----- Original Message -----

**Comment by nukulb** [comment]
I was thinking of recommending debug tokens as signing with invoke target has signing server restrictions 

------Original Message------

**Comment by mdandrea** [comment]
I did a full end-to-end test with the signed app.  Everything works fine (it looks like) if you just avoid using the "net.rim" prefix as your invoke target key.

**Comment by mdandrea** [comment]
On a related note, I was trying to figure this out yesterday afternoon.  If I make a change here, how does it ultimately get to https://github.com/blackberry/BB10-WebWorks-Samples?  I have read only permissions there, so I couldn't do a pull request there.

**Comment by nukulb** [comment]
That is expected. I will move it to the blackberry repo.
This is our working repo 
------Original Message------

**Comment by mdandrea** [comment]
Great, thank you!

**Comment by mdandrea** [comment]
Sorry to ask, but is this going to be merged shortly?  There's a bit of urgency because no one will be able to sign the Push Capture app without this fix.

**Comment by astanley** [comment]
Sorry I missed this one.  The pushCapture sample is now public in https://github.com/blackberry/BB10-WebWorks-Samples.  Can we get this change pushed there instead?

**Comment by mdandrea** [comment]
Yep, that's where I ultimately want this fix to end up.  I unfortunately have read only permissions for that repo.

**Comment by astanley** [comment]
Ah okay.  Let me try and get i sent through.

**Pull request merged**
